# Generated by Django 3.1.4 on 2020-12-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20201218_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['dia']},
        ),
    ]
