# Generated by Django 3.1.4 on 2020-12-18 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0006_auto_20201218_1754'),
        ('agenda', '0005_auto_20201218_1754'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('dia', 'medico')},
        ),
    ]
