# Generated by Django 3.1.4 on 2020-12-18 22:44

import agenda.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20201218_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.DateField(default=datetime.date.today, validators=[agenda.models.Agenda.validate_date]),
        ),
    ]
