# Generated by Django 3.1.4 on 2020-12-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_auto_20201218_2244'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together={('data_agendamento', 'horario')},
        ),
    ]
