# Generated by Django 3.1.4 on 2020-12-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('crm', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('telefone', models.CharField(max_length=255)),
                ('especialidades', models.ManyToManyField(to='medicos.Especialidade')),
            ],
        ),
    ]
