# Generated by Django 3.1.4 on 2020-12-18 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='especialidades',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidades',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='medicos.especialidade'),
        ),
    ]
