# Generated by Django 3.1.4 on 2020-12-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_auto_20201218_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medicos.especialidade'),
        ),
    ]
