# Generated by Django 3.1.4 on 2020-12-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0005_auto_20201218_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='especialidades',
            new_name='especialidade',
        ),
    ]
